// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Truck_Maintanance_system.Data;

#nullable disable

namespace Truck_Maintanance_system.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260825175733_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Truck_Maintanance_system.Models.MechanicalMaintenanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcCabinFilter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdBlueDefOil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AirCompressorAndValve")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AirFilter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BatteryAgeMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatteryConditionPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrakeFluid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrakeRotorDiscFront")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrakeRotorDiscRear")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrakeShoeDiscFront")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrakeShoeDiscRear")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClutchPlateAgeMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClutchPlateLifePercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Coolant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CrownAxelOil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateLogged")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineOil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelFilter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Greasing")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HydraulicFilter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HydraulicOil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OdometerKm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OilFilter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpareWheelCondition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransmissionOil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TruckId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TyreConditionPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TyrePressure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WaterSeparatorDieselFilter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WheelAlignment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TruckId");

                    b.ToTable("MechanicalMaintenanceRecords");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.MechanicalMaintenanceRecord", b =>
                {
                    b.HasOne("Truck_Maintanance_system.Models.Truck", "Truck")
                        .WithMany()
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Truck");
                });
#pragma warning restore 612, 618
        }
    }
}
