// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Truck_Maintanance_system.Data;

#nullable disable

namespace Truck_Maintanance_system.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260825192021_AddAlertSystem")]
    partial class AddAlertSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Truck_Maintanance_system.Models.AlertMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageText")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("AlertMessages");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.AlertTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TruckId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TruckId");

                    b.ToTable("AlertTickets");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.MechanicalMaintenanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateLogged")
                        .HasColumnType("TEXT");

                    b.Property<int>("OdometerKm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TruckId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValidForNextKm")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TruckId");

                    b.ToTable("MechanicalMaintenanceRecords");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.TruckDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT");

                    b.Property<int>("TruckId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TruckId");

                    b.ToTable("TruckDocuments");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.AlertMessage", b =>
                {
                    b.HasOne("Truck_Maintanance_system.Models.AlertTicket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.AlertTicket", b =>
                {
                    b.HasOne("Truck_Maintanance_system.Models.Truck", "Truck")
                        .WithMany()
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.MechanicalMaintenanceRecord", b =>
                {
                    b.HasOne("Truck_Maintanance_system.Models.Truck", "Truck")
                        .WithMany()
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "AcCabinFilter", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "AdBlueDefOil", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "AirCompressorAndValve", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "AirFilter", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "BatteryCondition", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "BrakeFluid", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "BrakeRotorDiscFront", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "BrakeRotorDiscRear", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "BrakeShoeDiscFront", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "BrakeShoeDiscRear", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "ClutchPlateLife", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "Coolant", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "CrownAxelOil", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "EngineOil", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "FuelFilter", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "Greasing", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "HydraulicFilter", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "HydraulicOil", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "OilFilter", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "SpareWheelCondition", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "TransmissionOil", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "TyreCondition", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "TyrePressure", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "WaterSeparatorDieselFilter", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "WheelAlignment", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.Navigation("AcCabinFilter")
                        .IsRequired();

                    b.Navigation("AdBlueDefOil")
                        .IsRequired();

                    b.Navigation("AirCompressorAndValve")
                        .IsRequired();

                    b.Navigation("AirFilter")
                        .IsRequired();

                    b.Navigation("BatteryCondition")
                        .IsRequired();

                    b.Navigation("BrakeFluid")
                        .IsRequired();

                    b.Navigation("BrakeRotorDiscFront")
                        .IsRequired();

                    b.Navigation("BrakeRotorDiscRear")
                        .IsRequired();

                    b.Navigation("BrakeShoeDiscFront")
                        .IsRequired();

                    b.Navigation("BrakeShoeDiscRear")
                        .IsRequired();

                    b.Navigation("ClutchPlateLife")
                        .IsRequired();

                    b.Navigation("Coolant")
                        .IsRequired();

                    b.Navigation("CrownAxelOil")
                        .IsRequired();

                    b.Navigation("EngineOil")
                        .IsRequired();

                    b.Navigation("FuelFilter")
                        .IsRequired();

                    b.Navigation("Greasing")
                        .IsRequired();

                    b.Navigation("HydraulicFilter")
                        .IsRequired();

                    b.Navigation("HydraulicOil")
                        .IsRequired();

                    b.Navigation("OilFilter")
                        .IsRequired();

                    b.Navigation("SpareWheelCondition")
                        .IsRequired();

                    b.Navigation("TransmissionOil")
                        .IsRequired();

                    b.Navigation("Truck");

                    b.Navigation("TyreCondition")
                        .IsRequired();

                    b.Navigation("TyrePressure")
                        .IsRequired();

                    b.Navigation("WaterSeparatorDieselFilter")
                        .IsRequired();

                    b.Navigation("WheelAlignment")
                        .IsRequired();
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.TruckDocument", b =>
                {
                    b.HasOne("Truck_Maintanance_system.Models.Truck", "Truck")
                        .WithMany()
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.AlertTicket", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
