// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Truck_Maintanance_system.Data;

#nullable disable

namespace Truck_Maintanance_system.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260830090855_AddSparePartsInventory")]
    partial class AddSparePartsInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.AlertMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageText")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("AlertMessages");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.AlertTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TruckId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TruckId");

                    b.ToTable("AlertTickets");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.FuelLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FuelDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelStation")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Liters")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("OdometerReading")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerLiter")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptImagePath")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("TruckId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FuelDate");

                    b.HasIndex("TruckId");

                    b.ToTable("FuelLogs");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.MechanicalMaintenanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateLogged")
                        .HasColumnType("TEXT");

                    b.Property<int>("OdometerKm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TruckId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValidForNextKm")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TruckId");

                    b.ToTable("MechanicalMaintenanceRecords");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.ServiceReminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DueOdometer")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IntervalKm")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IntervalMonths")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastServicedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastServicedOdometer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TruckId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("Status");

                    b.HasIndex("TruckId");

                    b.ToTable("ServiceReminders");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.SparePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRestockedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationBin")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("MinReorderLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("PartNumber");

                    b.ToTable("SpareParts");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.SparePartUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobReference")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SparePartId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TruckId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UsageDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SparePartId");

                    b.HasIndex("TruckId");

                    b.HasIndex("UsageDate");

                    b.ToTable("SparePartUsages");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.TripLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TripId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("TripLocations");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.TripRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DriverAllowance")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FreightRevenue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FuelCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FuelVolumeLiters")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OtherExpenses")
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteEnd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TollCost")
                        .HasColumnType("TEXT");

                    b.Property<int>("TruckId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("TruckId");

                    b.ToTable("TripRecords");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentOdometer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.TruckDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT");

                    b.Property<int>("TruckId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TruckId");

                    b.ToTable("TruckDocuments");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.TyreInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AxlePosition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InstallationOdometer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchaseCost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TreadDepthMm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TruckId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber");

                    b.HasIndex("TruckId");

                    b.ToTable("TyreInventories");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.VehicleInspectionReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BrakesOk")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectiveActionTaken")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefectsDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EngineOilAndFluidsOk")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSafeToOperate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LightsAndSignalsOk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OdometerReading")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SteeringAndHornOk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TruckId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TyresAndWheelsOk")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WipersAndGlassOk")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InspectionDate");

                    b.HasIndex("TruckId");

                    b.ToTable("VehicleInspections");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.AlertMessage", b =>
                {
                    b.HasOne("Truck_Maintanance_system.Models.AlertTicket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.AlertTicket", b =>
                {
                    b.HasOne("Truck_Maintanance_system.Models.Truck", "Truck")
                        .WithMany("AlertTickets")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.FuelLog", b =>
                {
                    b.HasOne("Truck_Maintanance_system.Models.Truck", "Truck")
                        .WithMany("FuelLogs")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.MechanicalMaintenanceRecord", b =>
                {
                    b.HasOne("Truck_Maintanance_system.Models.Truck", "Truck")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "AcCabinFilter", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "AdBlueDefOil", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "AirCompressorAndValve", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "AirFilter", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "BatteryCondition", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "BrakeFluid", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "BrakeRotorDiscFront", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "BrakeRotorDiscRear", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "BrakeShoeDiscFront", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "BrakeShoeDiscRear", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "ClutchPlateLife", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "Coolant", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "CrownAxelOil", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "EngineOil", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "FuelFilter", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "Greasing", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "HydraulicFilter", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "HydraulicOil", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "OilFilter", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "SpareWheelCondition", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "TransmissionOil", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "TyreCondition", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "TyrePressure", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "WaterSeparatorDieselFilter", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.OwnsOne("Truck_Maintanance_system.Models.MaintenanceItemDetails", "WheelAlignment", b1 =>
                        {
                            b1.Property<int>("MechanicalMaintenanceRecordId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ValidForNextDate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ValidForNextKm")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MechanicalMaintenanceRecordId");

                            b1.ToTable("MechanicalMaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MechanicalMaintenanceRecordId");
                        });

                    b.Navigation("AcCabinFilter")
                        .IsRequired();

                    b.Navigation("AdBlueDefOil")
                        .IsRequired();

                    b.Navigation("AirCompressorAndValve")
                        .IsRequired();

                    b.Navigation("AirFilter")
                        .IsRequired();

                    b.Navigation("BatteryCondition")
                        .IsRequired();

                    b.Navigation("BrakeFluid")
                        .IsRequired();

                    b.Navigation("BrakeRotorDiscFront")
                        .IsRequired();

                    b.Navigation("BrakeRotorDiscRear")
                        .IsRequired();

                    b.Navigation("BrakeShoeDiscFront")
                        .IsRequired();

                    b.Navigation("BrakeShoeDiscRear")
                        .IsRequired();

                    b.Navigation("ClutchPlateLife")
                        .IsRequired();

                    b.Navigation("Coolant")
                        .IsRequired();

                    b.Navigation("CrownAxelOil")
                        .IsRequired();

                    b.Navigation("EngineOil")
                        .IsRequired();

                    b.Navigation("FuelFilter")
                        .IsRequired();

                    b.Navigation("Greasing")
                        .IsRequired();

                    b.Navigation("HydraulicFilter")
                        .IsRequired();

                    b.Navigation("HydraulicOil")
                        .IsRequired();

                    b.Navigation("OilFilter")
                        .IsRequired();

                    b.Navigation("SpareWheelCondition")
                        .IsRequired();

                    b.Navigation("TransmissionOil")
                        .IsRequired();

                    b.Navigation("Truck");

                    b.Navigation("TyreCondition")
                        .IsRequired();

                    b.Navigation("TyrePressure")
                        .IsRequired();

                    b.Navigation("WaterSeparatorDieselFilter")
                        .IsRequired();

                    b.Navigation("WheelAlignment")
                        .IsRequired();
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.ServiceReminder", b =>
                {
                    b.HasOne("Truck_Maintanance_system.Models.Truck", "Truck")
                        .WithMany("ServiceReminders")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.SparePartUsage", b =>
                {
                    b.HasOne("Truck_Maintanance_system.Models.SparePart", "SparePart")
                        .WithMany("Usages")
                        .HasForeignKey("SparePartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Truck_Maintanance_system.Models.Truck", "Truck")
                        .WithMany("SparePartUsages")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SparePart");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.TripLocation", b =>
                {
                    b.HasOne("Truck_Maintanance_system.Models.TripRecord", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.TripRecord", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId");

                    b.HasOne("Truck_Maintanance_system.Models.Truck", "Truck")
                        .WithMany("Trips")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.TruckDocument", b =>
                {
                    b.HasOne("Truck_Maintanance_system.Models.Truck", "Truck")
                        .WithMany("Documents")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.TyreInventory", b =>
                {
                    b.HasOne("Truck_Maintanance_system.Models.Truck", "Truck")
                        .WithMany("Tyres")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.VehicleInspectionReport", b =>
                {
                    b.HasOne("Truck_Maintanance_system.Models.Truck", "Truck")
                        .WithMany("Inspections")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.AlertTicket", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.SparePart", b =>
                {
                    b.Navigation("Usages");
                });

            modelBuilder.Entity("Truck_Maintanance_system.Models.Truck", b =>
                {
                    b.Navigation("AlertTickets");

                    b.Navigation("Documents");

                    b.Navigation("FuelLogs");

                    b.Navigation("Inspections");

                    b.Navigation("MaintenanceRecords");

                    b.Navigation("ServiceReminders");

                    b.Navigation("SparePartUsages");

                    b.Navigation("Trips");

                    b.Navigation("Tyres");
                });
#pragma warning restore 612, 618
        }
    }
}
